version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python environment"

  build:
    commands:
      - echo "Running Python Program..."
      - python python/numbers_analysis.py

artifacts:
  files:
    - '**/*'
