name: Deploy Java Project to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy Java Project to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no \
          -i private_key.pem \
          java-project \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Verify Files on EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i private_key.pem \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
          "ls -R /home/ubuntu/java-project"
